package com.noveltea.web;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.fail;

import com.noveltea.support.AbstractPostgresTest;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.web.servlet.mvc.method.RequestMappingInfo;
import org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping;
import org.yaml.snakeyaml.Yaml;

/**
 * Holds {@code docs/api/openapi.yaml} to the handler mapping.
 *
 * <p>The spec is generated by {@code ./gradlew :api:generateOpenApiDocs}, which boots the
 * application in a forked JVM and scrapes it — so it needs a reachable Postgres, and a
 * contributor without one running will not have regenerated it. This test needs neither:
 * it reads the routes out of the same mapping the application serves and compares them to
 * the file that is checked in, so a controller method added without regenerating fails
 * here rather than shipping an OpenAPI document that quietly omits it.
 *
 * <p>It is the same shape as {@code EnumSchemaAlignmentTest} and {@code IdorSweepTest}:
 * two declarations of one fact in different languages, with a test that keeps them honest.
 * Both directions are checked — a route missing from the spec, and a spec entry for a route
 * that no longer exists.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.MOCK)
class OpenApiSpecFreshnessTest extends AbstractPostgresTest {

    /**
     * Routes the document covers. Anything springdoc itself contributes is excluded: those
     * are disabled under the test profile and are not part of the API being described.
     */
    private static final Set<String> DOCUMENTED_PREFIXES = Set.of("/api/v1", "/health");

    @Autowired RequestMappingHandlerMapping handlerMapping;

    /** Resolved from the working directory, which Gradle sets to the :api project dir. */
    private static Path specPath() {
        for (Path candidate :
                new Path[] {Path.of("docs/api/openapi.yaml"), Path.of("../docs/api/openapi.yaml")}) {
            if (Files.isRegularFile(candidate)) return candidate;
        }
        return fail("docs/api/openapi.yaml not found from " + Path.of("").toAbsolutePath());
    }

    /** "GET /api/v1/projects" for every route the application actually maps. */
    private Set<String> mappedRoutes() {
        Set<String> routes = new TreeSet<>();
        for (RequestMappingInfo info : handlerMapping.getHandlerMethods().keySet()) {
            Set<String> patterns = info.getPatternValues();
            Set<org.springframework.web.bind.annotation.RequestMethod> methods =
                    info.getMethodsCondition().getMethods();
            for (String pattern : patterns) {
                if (DOCUMENTED_PREFIXES.stream().noneMatch(pattern::startsWith)) continue;
                if (methods.isEmpty()) {
                    // A mapping with no method condition answers every verb. Nothing in this
                    // API does that today, and a spec cannot express it, so say so loudly.
                    fail("Route " + pattern + " maps no explicit HTTP method; the spec cannot"
                            + " represent it. Give it one.");
                }
                methods.forEach(m -> routes.add(m.name() + " " + pattern));
            }
        }
        return routes;
    }

    /** "GET /api/v1/projects" for every operation the checked-in document declares. */
    private static Set<String> specifiedRoutes() throws IOException {
        Object loaded;
        try (var reader = Files.newBufferedReader(specPath())) {
            loaded = new Yaml().load(reader);
        }
        assertThat(loaded).as("openapi.yaml did not parse as a mapping").isInstanceOf(Map.class);

        Object paths = ((Map<?, ?>) loaded).get("paths");
        assertThat(paths).as("openapi.yaml declares no paths").isInstanceOf(Map.class);

        Set<String> routes = new TreeSet<>();
        ((Map<?, ?>) paths)
                .forEach((path, operations) -> {
                    if (!(operations instanceof Map<?, ?> byMethod)) return;
                    byMethod.keySet().stream()
                            .map(String::valueOf)
                            // "parameters" and "summary" are siblings of the verbs.
                            .filter(key -> Set.of(
                                            "get", "put", "post", "delete", "patch", "head",
                                            "options", "trace")
                                    .contains(key))
                            .forEach(verb ->
                                    routes.add(verb.toUpperCase(Locale.ROOT) + " " + path));
                });
        return routes;
    }

    @Test
    @DisplayName("every mapped route appears in the checked-in OpenAPI document")
    void specCoversEveryRoute() throws IOException {
        assertThat(mappedRoutes())
                .as("Routes the application serves but docs/api/openapi.yaml omits. "
                        + "Start Postgres and run ./gradlew :api:generateOpenApiDocs, then "
                        + "commit the regenerated file.")
                .isSubsetOf(specifiedRoutes());
    }

    @Test
    @DisplayName("the OpenAPI document describes no route the application no longer serves")
    void specHasNoStaleRoutes() throws IOException {
        assertThat(specifiedRoutes())
                .as("Routes docs/api/openapi.yaml still describes but the application no longer "
                        + "maps. Regenerate the spec with ./gradlew :api:generateOpenApiDocs.")
                .isSubsetOf(mappedRoutes());
    }

    @Test
    @DisplayName("the sweep is actually looking at routes")
    void guardsItself() throws IOException {
        // Without this, a mapping-enumeration bug that returned nothing would make both
        // assertions above pass vacuously — the failure mode these tests exist to catch.
        assertThat(mappedRoutes()).hasSizeGreaterThan(30);
        assertThat(specifiedRoutes()).hasSizeGreaterThan(30);
    }
}
