--liquibase formatted sql

--changeset anthony:20260818-12-01-change-log
--comment: Append-only feed backing the sync protocol. Every mutation to a synced
--comment: entity appends exactly one row here, in the same transaction as the write.
--comment:
--comment: WHY tx_id EXISTS (A5). `id` is the client's cursor, but `id` alone is an
--comment: unsafe read predicate: sequence values are handed out at INSERT and only
--comment: become visible at COMMIT, so a transaction holding id 100 can commit after
--comment: one holding 101. A client that has seen 101 and asks for `id > 101` would
--comment: skip 100 permanently. tx_id records the writing transaction so readers can
--comment: exclude anything not yet known-committed to every observer:
--comment:
--comment:   SELECT * FROM change_log
--comment:    WHERE project_id = :projectId
--comment:      AND id > :since
--comment:      AND tx_id < pg_snapshot_xmin(pg_current_snapshot())
--comment:    ORDER BY id;
--comment:
--comment: Keep that predicate in exactly one query method. Two copies means one of
--comment: them eventually loses the tx_id clause.
CREATE TABLE change_log (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_id          xid8        NOT NULL DEFAULT pg_current_xact_id(),
    project_id     uuid        NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    entity_type    text        NOT NULL,
    entity_id      uuid        NOT NULL,
    op             text        NOT NULL,
    device_id      uuid        REFERENCES device(id) ON DELETE SET NULL,
    actor_user_id  uuid        REFERENCES app_user(id) ON DELETE SET NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT change_log_op_valid
        CHECK (op IN ('create', 'update', 'delete')),
    CONSTRAINT change_log_entity_type_valid
        CHECK (entity_type IN (
            'binder_item',
            'document',
            'taxonomy',
            'custom_metadata_field',
            'custom_metadata_value',
            'collection',
            'collection_item',
            'compile_preset',
            'project_member'
        ))
);

-- Primary sync read path: ordered scan within a project, gated on tx_id.
CREATE INDEX change_log_feed_idx ON change_log (project_id, id) INCLUDE (tx_id);

-- Supports resolving "what happened to this entity" during conflict handling.
CREATE INDEX change_log_entity_idx ON change_log (entity_type, entity_id, id DESC);
--rollback DROP TABLE change_log;
